### ISSUE TITLE
Date Field

### ISSUE THREAD

**Issue by bcbisme** [rajyraman/mscrmexporttoexcel#12]
We are having an issue with the date field that is reporting the wrong date.  It is off by (-1) date in the US.  Say we have the EOM date of 7/31/2019  12:00:00 AM the export is stating 7/30/2019 7:00:00 PM .  We assume it has something to do with UTC, but how can we change this in Export to Excel?

**Comment by rajyraman** [comment]
I checked the sourcecode and I am converting from utc to local -> https://github.com/rajyraman/mscrmexporttoexcel/blob/master/Ryr.XrmToolBox.Plugins/Ryr.ExcelExport/ExcelExportPlugin.cs#L445.

Is this the latest version of the plugin and is the Windows timezone correct?

**Comment by bcbisme** [comment]
That is correct.  And thank you for such a quick response.  ☺

**Comment by rajyraman** [comment]
Correct as in the issue is resolved or that you are using the latest version and the windows/user settings timezone are all correct?

**Comment by bcbisme** [comment]
I apologize, The correct was for:  As in that they are all the latest versions and the timezone are is set properly.

**Comment by rajyraman** [comment]
I will check it this week. Usually ToLocalTimeZone should just work. Did you check how it comes through in FetchXML Builder?

**Comment by bcbisme** [comment]
Yes, we check it thru FetchXML and it is working  as expected, giving us the proper time and date.

**Comment by rajyraman** [comment]
FetchXML or FetchXML Builder? Are you saying that it is displaying correctly in FetchXML Builder or not when you export it out?
![image](https://user-images.githubusercontent.com/5035266/54239904-afd2eb00-4570-11e9-8586-1209bc08c644.png)

**Comment by bcbisme** [comment]
It is thru FetchXML Builder version 1.2019.3.6 and it is displaying correctly
[cid:image002.png@01D4D8F8.430E59D0]
Export to Excel
[cid:image003.png@01D4D8F8.430E59D0]

**Comment by rajyraman** [comment]
I checked this and it is the other way round - export to excel is correct and FXB is incorrect. See screenshots below. can you please post some screenshots?

![image](https://user-images.githubusercontent.com/5035266/54274010-302e3600-45db-11e9-88c3-9df125bcb180.png)
![image](https://user-images.githubusercontent.com/5035266/54274040-3d4b2500-45db-11e9-8b32-21b37207c8d5.png)
![image](https://user-images.githubusercontent.com/5035266/54274023-36bcad80-45db-11e9-9b87-c344498d7301.png)

**Comment by bcbisme** [comment]
Here is what is in D365
[cid:image001.png@01D4D964.A98A30F0]

[cid:image002.png@01D4D964.A98A30F0]
[cid:image003.png@01D4D964.A98A30F0]


[cid:image004.png@01D4D964.A98A30F0]

**Comment by rajyraman** [comment]
I cannot see any images.

**Comment by bcbisme** [comment]
Here is what is in D365
[cid:image001.png@01D4D9CD.F7AA4040]

[cid:image002.png@01D4D9CD.F7AA4040]
[cid:image003.png@01D4D9CD.F7AA4040]


[cid:image004.png@01D4D9CD.F7AA4040]

**Comment by rajyraman** [comment]
I still cannot see the images. Can you please upload them from GitHub?

**Comment by StillLearning1** [comment]
Hi, I am having a similar issue where dates are being converted to Local Time Zone, and since the date fields have "Behavior = Date Only", the time portion is always midnight (12:00 AM) and the exported Date values always appears as the previous day with time = "19:00" (we are in EST which is UTC - 5).

Is it possible to have your utility not convert to Local Time Zone, or provide a checkbox which would let us choose "UTC" or "Local Timezone"?

**Comment by rajyraman** [comment]
@StillLearning1 - I have added some code to the latest commit to use ToLocalTime(), only when the Kind is UTC. I hope that will fix the issue. If not, please let me know. I will push this to nuget later in the day.
