### ISSUE TITLE
Missing file error  EPPlus, Version=4.1.1.0

### ISSUE THREAD

**Issue by QuiltyGal** [rajyraman/mscrmexporttoexcel#13]
Greetings,
Am exporting 6100 records and all seems to go well until the tool tries to write to Excel. I get the following message:

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'EPPlus, Version=4.1.1.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' or one of its dependencies. The system cannot find the file specified.
File name: 'EPPlus, Version=4.1.1.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1'
   at Ryr.ExcelExport.ExcelExportPlugin.WriteToExcel(List`1 headers, List`1 rows, String fileName)
   at Ryr.ExcelExport.ExcelExportPlugin.<>c__DisplayClass14_0.<ExportCurrentViewToExcel>b__0(BackgroundWorker w, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

and with this error is a list of loaded assemblies ( i have removed the version data but could provide if needed)

AndyPopkin.BulkDeleteTool
--
Anonymously Hosted DynamicMethods   Assembly
BulkAddressVerifier
BulkAttachmentManagementPlugin
Carfup.XTBPlugins.PersonalViewsMigration
Colso.Xrm.DashboardTransferTool
DamSim.SolutionTransferTool
DamSim.ViewTransferTool
DescriptionAndTags
EPPlus
GapConsulting.PowerBIOptionSetAssistant
ICSharpCode.TextEditor
ITLecChartGuy.AdvancedChartEditor
Javista.XrmToolBox.ImportNN
McTools.StopAdvertisement
McTools.Xrm.Connection
McTools.Xrm.Connection.WinForms
MetadataViewProxies_8f5ffea6-942d-43fc-98db-9e68d09bb2eb
Microsoft.Crm.Sdk.Proxy
Microsoft.GeneratedCode
Microsoft.IdentityModel
Microsoft.IdentityModel.Clients.ActiveDirectory
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
Microsoft.VisualBasic
Microsoft.Xrm.Sdk
Microsoft.Xrm.Sdk.Deployment
Microsoft.Xrm.Sdk.Workflow
Microsoft.Xrm.Tooling.Connector
Microsoft.Xrm.Tooling.CrmConnectControl
Microsoft.Xrm.Tooling.Ui.Styles
mscorlib
MsCrmTools.AccessChecker
MsCrmTools.AssemblyRecoveryTool
MsCrmTools.AttributeBulkUpdater
MscrmTools.AttributeUsageInspector
MsCrmTools.AuditCenter
MsCrmTools.ChartManager
MscrmTools.CrmTraceReader
MsCrmTools.DocumentTemplatesMover
MsCrmTools.FetchXmlTester
MsCrmTools.FlsBulkUpdater
MsCrmTools.FormRelated
MsCrmTools.Iconator
MscrmTools.ManagedSolutionDeletionTool
MsCrmTools.MetadataBrowser
MsCrmTools.MetadataDocumentGenerator
MscrmTools.PortalCodeEditor
MscrmTools.PortalRecordsMover
MsCrmTools.SampleTool
MsCrmTools.ScriptsFinder
MsCrmTools.SecurityRelated
MsCrmTools.SiteMapEditor
MsCrmTools.SolutionComponentsMover
MsCrmTools.SolutionImport
MscrmTools.SyncFilterManager
MsCrmTools.SynchronousEventOrderEditor
MsCrmTools.Translator
MsCrmTools.UserSettingsUtility
MsCrmTools.ViewLayoutReplicator
MscrmTools.WebresourcesManager
MsDyn.Contrib.CloneFieldDefinitions
Newtonsoft.Json
Norriq.XrmToolBox.Facilities
Norriq.XrmToolBox.Facilities.Tooling
Norriq.XrmToolBox.Facilities.Xrm
Norriq.XrmToolBox.Facilities.Xrm.Tooling
Norriq.XrmToolBox.YourEntityAttributeMappingsCustomized
NuGet.Core
NZ.XrmToolbox.PersonalArtefactManager
Personalview
PresentationCore
PresentationFramework
Rappen.XTB.FXB
Ryr.ExcelExport
SMDiagnostics
System
System.ComponentModel.Composition
System.ComponentModel.DataAnnotations
System.Configuration
System.Core
System.Data
System.Data.Services.Client
System.Deployment
System.Design
System.Drawing
System.IdentityModel
System.IdentityModel.Selectors
System.IO.Compression.FileSystem
System.Net.Http
System.Runtime.Serialization
System.Security
System.ServiceModel
System.ServiceModel.Channels
System.ServiceModel.Internals
System.Web
System.Web.Services
System.Windows.Forms
System.Xaml
System.Xml
System.Xml.Linq
Thrives.XrmToolBox.EntityUsage
ViewRoleConfiguration
WeifenLuo.WinFormsUI.Docking
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
WindowsBase
XrmToolBox
XrmToolBox.Extensibility
XrmToolbox.JavascriptValidator
XrmToolBox.PluginsStore

I am provided the option to Continue or Quit.   
If I continue, i do not get an export file ad nothing else happens.
This is the fetch, but I believe it is ok.

<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" >
  <entity name="opportunity" >
    <attribute name="name" />
    <attribute name="estimatedvalue" />
    <attribute name="estimatedclosedate" />
    <attribute name="parentaccountid" />
    <attribute name="new_segement" />
    <attribute name="opportunityid" />
    <attribute name="new_workpermitdetails" />
    <attribute name="new_zld" />
    <attribute name="new_wasteconnectionsize" />
    <attribute name="new_wasteconnectionfitting" />
    <attribute name="new_volumerebateproposed" />
    <attribute name="new_uploadedwrittenconfirmation" />
    <attribute name="new_uploadedpo" />
    <attribute name="new_uploadjdssale" />
    <attribute name="new_ulrfq" />
    <attribute name="new_sourceturbidity" />
    <attribute name="new_finishedturbidity" />
    <attribute name="new_trainingrequiredyn" />
    <attribute name="new_sourcehardness" />
    <attribute name="timeline" />
    <attribute name="new_termsconditionsapproved" />
    <attribute name="new_termsconditions" />
    <attribute name="new_templateform" />
    <attribute name="new_technicalengineeringapprovaltecheng" />
    <attribute name="teamsfollowed" />
    <attribute name="new_tankvolumeg" />
    <attribute name="new_tanklevelcontrol" />
    <attribute name="new_tankheightft" />
    <attribute name="new_tcs" />
    <attribute name="new_supplywatersource" />
    <attribute name="new_supply_ph" />
    <attribute name="stepid" />
    <attribute name="new_customstatusreason" />
    <attribute name="statecode" />
    <attribute name="new_startserviceformuploaded" />
    <attribute name="new_standardtscssent" />
    <attribute name="new_specialstaffing" />
    <attribute name="new_sourcewaterpressure" />
    <attribute name="new_sourceconnectionsize" />
    <attribute name="new_sourceconnectionfitting" />
    <attribute name="new_sourcechloramineyn" />
    <attribute name="new_sitespecifictrainingrequiredyn" />
    <attribute name="new_sitespecifictrainingdetails" />
    <attribute name="new_sitevisitrequired" />
    <attribute name="new_sitesurvey" />
    <attribute name="new_simplifiedstatusreason" />
    <attribute name="new_sdi" />
    <attribute name="new_finishedsilica" />
    <attribute name="new_sourcesilica" />
    <attribute name="new_servicetype2" />
    <attribute name="new_customerneed2" />
    <attribute name="new_customerneed1" />
    <attribute name="new_customerneed" />
    <attribute name="new_servicetype" />
    <attribute name="sendthankyounote" />
    <attribute name="schedulefollowup_qualify" />
    <attribute name="schedulefollowup_prospect" />
    <attribute name="scheduleproposalmeeting" />
    <attribute name="new_schedulejobwopperations" />
    <attribute name="new_h2osampleshipdate" />
    <attribute name="new_h2otestlab" />
    <attribute name="new_salesstage" />
    <attribute name="new_rfqscopedefinedinproposal" />
    <attribute name="new_rqfquestionsubmitted" />
    <attribute name="new_revenuefrequency" />
    <attribute name="isrevenuesystemcalculated" />
    <attribute name="new_requiredtraining" />
    <attribute name="new_mpwprovidedchemicals" />
    <attribute name="new_remoteaccessyn" />
    <attribute name="new_refresh" />
    <attribute name="overriddencreatedon" />
    <attribute name="new_recirclineyn" />
    <attribute name="new_receivedpo" />
    <attribute name="opportunityratingcode" />
    <attribute name="new_ratesestablishedsalebd" />
    <attribute name="new_ratesdefined" />
    <attribute name="new_quotecounter_oppid" />
    <attribute name="new_quotewrittensalesbd" />
    <attribute name="new_quoteuploadedsalesbd" />
    <attribute name="new_quotenumber" />
    <attribute name="quotecomments" />
    <attribute name="new_quoteapprovedmgr" />
    <attribute name="new_quoteapprovedengmgr" />
    <attribute name="qualificationcomments" />
    <attribute name="purchasetimeframe" />
    <attribute name="purchaseprocess" />
    <attribute name="new_pumpmodelnumber" />
    <attribute name="new_pumpbrandname" />
    <attribute name="new_prv_yn" />
    <attribute name="new_custprovidedchemicals" />
    <attribute name="new_prospectcontact" />
    <attribute name="proposedsolution" />
    <attribute name="new_proposaltype" />
    <attribute name="new_proposalsubmitted" />
    <attribute name="captureproposalfeedback" />
    <attribute name="new_proposalduedate" />
    <attribute name="new_projecttype" />
    <attribute name="new_projecttiming" />
    <attribute name="new_projectperiod" />
    <attribute name="new_productconnectionsize" />
    <attribute name="new_productconnectionfitting" />
    <attribute name="stageid" />
    <attribute name="new_processflowdiagram" />
    <attribute name="salesstagecode" />
    <attribute name="processid" />
    <attribute name="new_probability" />
    <attribute name="prioritycode" />
    <attribute name="new_pricinguploadedeng" />
    <attribute name="new_pricingapprovedgm" />
    <attribute name="new_pricingsales" />
    <attribute name="new_pricing" />
    <attribute name="new_pricing3" />
    <attribute name="pricelevelid" />
    <attribute name="new_pretreatment" />
    <attribute name="new_preserviceformuploaded" />
    <attribute name="new_presentedtoprospect" />
    <attribute name="presentproposal" />
    <attribute name="presentfinalproposal" />
    <attribute name="new_prequalification" />
    <attribute name="new_poweravailable" />
    <attribute name="customerid" />
    <attribute name="new_po_nbr" />
    <attribute name="new_ponumber" />
    <attribute name="new_platformworkflow" />
    <attribute name="new_platform" />
    <attribute name="stepname" />
    <attribute name="ps_phonenumber" />
    <attribute name="new_paymentterms" />
    <attribute name="ownerid" />
    <attribute name="new_other" />
    <attribute name="originatingleadid" />
    <attribute name="new_opportunitytype" />
    <attribute name="statuscode" />
    <attribute name="new_obstacles" />
    <attribute name="new_obstaclestrength" />
    <attribute name="new_nextfollowupdate" />
    <attribute name="new_contractname2" />
    <attribute name="new_needlegal" />
    <attribute name="new_needengineering" />
    <attribute name="new_needcorpbusdev" />
    <attribute name="need" />
    <attribute name="new_natureofbusiness" />
    <attribute name="new_msa" />
    <attribute name="new_mpwprequalification" />
    <attribute name="new_mpwbranchassociate" />
    <attribute name="modifiedon" />
    <attribute name="modifiedby" />
    <attribute name="new_sourcetempmin" />
    <attribute name="new_pumpminimumpressure" />
    <attribute name="new_meetwithprospect" />
    <attribute name="new_sourcetempmax" />
    <attribute name="new_pumpmaximumpressure" />
    <attribute name="new_polengthofjob" />
    <attribute name="new_legalredlinesent" />
    <attribute name="new_leadsourceparent" />
    <attribute name="new_leadsourcenew" />
    <attribute name="new_lastcontacted" />
    <attribute name="new_jobwalkdown" />
    <attribute name="new_jobstartmonth" />
    <attribute name="new_jobstartdate" />
    <attribute name="initialcommunication" />
    <attribute name="identifypursuitteam" />
    <attribute name="identifycustomercontacts" />
    <attribute name="identifycompetitors" />
    <attribute name="new_icgstaffing" />
    <attribute name="new_hasvfdyn" />
    <attribute name="new_formalrfqprovided" />
    <attribute name="msdyn_forecastcategory" />
    <attribute name="new_flowrategpm" />
    <attribute name="new_fieldservicefrequency" />
    <attribute name="new_flag" />
    <attribute name="new_finishedvolume" />
    <attribute name="new_financials" />
    <attribute name="completefinalproposal" />
    <attribute name="finaldecisiondate" />
    <attribute name="filedebrief" />
    <attribute name="resolvefeedback" />
    <attribute name="new_expirationdate" />
    <attribute name="exchangerate" />
    <attribute name="evaluatefit" />
    <attribute name="estimatedvalue_base" />
    <attribute name="new_estmonthlyvalue_base" />
    <attribute name="new_estmonthlyvalue" />
    <attribute name="new_estclosemonths" />
    <attribute name="new_estyear" />
    <attribute name="new_equipmentpids" />
    <attribute name="new_engineer" />
    <attribute name="new_engmgr" />
    <attribute name="new_engdeliverablesuploaded" />
    <attribute name="new_enduse" />
    <attribute name="emailaddress" />
    <attribute name="new_durationmonths" />
    <attribute name="new_drugscreenrequiredyn" />
    <attribute name="new_drugscreendetails" />
    <attribute name="new_districtname" />
    <attribute name="new_distancetowastefeet" />
    <attribute name="new_distancetooutletfeet" />
    <attribute name="new_distancetoinletfeet" />
    <attribute name="new_diservicetype" />
    <attribute name="developproposal" />
    <attribute name="description" />
    <attribute name="new_demonstratedcapability" />
    <attribute name="decisionmaker" />
    <attribute name="pursuitdecision" />
    <attribute name="new_rfqclarificationdeadline" />
    <attribute name="new_data2customer" />
    <attribute name="new_permitrequiredyn" />
    <attribute name="new_permitdetails" />
    <attribute name="customerpainpoints" />
    <attribute name="customerneed" />
    <attribute name="new_customerform" />
    <attribute name="budgetamount" />
    <attribute name="currentsituation" />
    <attribute name="transactioncurrencyid" />
    <attribute name="createdon" />
    <attribute name="createdby" />
    <attribute name="new_createquotenumber" />
    <attribute name="new_createjdssale" />
    <attribute name="new_contractsent2eng" />
    <attribute name="new_contractname" />
    <attribute name="new_contractduration" />
    <attribute name="parentcontactid" />
    <attribute name="new_confirmjobstartdate" />
    <attribute name="confirminterest" />
    <attribute name="new_sourceconductivity" />
    <attribute name="new_finishedconductivity" />
    <attribute name="completeinternalreview" />
    <attribute name="new_compposition" />
    <attribute name="new_competitor" />
    <attribute name="new_commercialoffertype" />
    <attribute name="new_closedate" />
    <attribute name="new_sourcechloramineppm" />
    <attribute name="new_chemicalsrequiredyn" />
    <attribute name="new_chemicalsprovidedyn" />
    <attribute name="new_capitalwom" />
    <attribute name="budgetamount_base" />
    <attribute name="budgetstatus" />
    <attribute name="new_branchnames" />
    <attribute name="new_boosterpumprequired" />
    <attribute name="new_boosterpumpreqrdyn" />
    <attribute name="new_bigopportunityalert" />
    <attribute name="new_bidapprovalul" />
    <attribute name="new_backgroundcheckrequiredyn" />
    <attribute name="new_backgroundcheckdetails" />
    <attribute name="new_backpressure" />
    <attribute name="new_awardedto" />
    <attribute name="new_apcontactassigned" />
    <attribute name="new_h20resultsrecvdyn" />
    <attribute name="new_sourcealkalinity" />
    <attribute name="new_finishedaddlreqs" />
    <attribute name="new_addppe" />
    <attribute name="new_addlhardware" />
    <attribute name="actualvalue" />
    <attribute name="actualclosedate" />
    <order attribute="estimatedclosedate" descending="false" />
    <filter type="and" >
      <condition attribute="parentaccountid" operator="not-null" />
      <filter type="or" >
        <condition attribute="estimatedclosedate" operator="next-x-years" value="3" />
        <condition attribute="actualclosedate" operator="last-x-years" value="3" />
      </filter>
    </filter>
  </entity>
</fetch>

 
Thank you in advance for looking into this. 
QuiltyGal

**Comment by QuiltyGal** [comment]
Also, I have tried various batch size values but that has not helped.

**Comment by rajyraman** [comment]
Can you check on the XrmToolBox storage folder whether you have the EPPlus assembly?

![image](https://user-images.githubusercontent.com/5035266/61264773-0d05d400-a7d1-11e9-9248-500cc92812d6.png)

**Comment by rajyraman** [comment]
I am not sure why it is missing as the assembly is definitely in the nuget package.
![image](https://user-images.githubusercontent.com/5035266/61264881-679f3000-a7d1-11e9-9142-9d97b333c422.png)

**Comment by AndreCavaca** [comment]
EPPlus Version 4.1.1.0 has a dependency on ole32.dll which is not deployed with the nuget package.
A quickfix to this issue is to copy this dll from Windows folder. Actually in my windows folder there were many versions of this dll, I've used the one with 23.1KB:

![image](https://user-images.githubusercontent.com/40573887/64386476-212bbc00-d031-11e9-85c9-8454dc75f276.png)

Copy it and paste it in XrmToolBox plugin folder ~\Users\YourUser\AppData\Roaming\MscrmTools\XrmToolBox\Plugins and the error goes away.

The most recent version of EPPlus, which at the time I'm writing this is v4.5.3.2, no longer has this dependency.

**Comment by EHulburd** [comment]
I've just downloaded, and also having this issue. @AndreCavaca 's fix worked, but I also needed to restart XrmToolbox first.

**Comment by seanmcne** [comment]
Is there an intent to fix this bug?

**Comment by rajyraman** [comment]
Thank you for identifying the underlying issue @AndreCavaca. I have now updated EPPlus to the latest version. The licence of EPPlus has changed https://www.epplussoftware.com/Home/LgplToPolyform @seanmcne, @EHulburd.

I will push this to nuget later in the day.

**Comment by rajyraman** [comment]
You should be able to update the tool now.
![image](https://user-images.githubusercontent.com/5035266/78860404-7a4f4880-7a75-11ea-9012-2b4e178832e2.png)
