### ISSUE TITLE
EPPlus 5.1 is missing

### ISSUE THREAD

**Issue by MscrmTools** [rajyraman/mscrmexporttoexcel#15]
With latest version, it seems EPPlus 5.1 is missing from the assembly making it impossible to export data

---
- Deployment: Online
- DB Version: 9.1.0.20158
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 2.6.0.0

**Comment by rajyraman** [comment]
@MscrmTools  - This long standing issue is fixed in v2.8.3. Thank you to @BetimBeja for the help. Please update the plugin through XrmToolBox.
