### ISSUE TITLE
Error Message when trying to Export

### ISSUE THREAD

**Issue by as080388** [rajyraman/mscrmexporttoexcel#18]
Hello, this tool is so helpful and it was working fine until it suddenly started exporting data across a number of different excel files (when there were only just over 100K rows in the AF). I uninstalled the application and then re-installed and now getting this error message. Advice asap would be super.
![Export to Excel - error message](https://user-images.githubusercontent.com/79265812/108370892-151bc600-71f5-11eb-81fc-750755be3252.jpg)

**Comment by MaTeMaTuK** [comment]
Hi @as080388,
I have registred EPPlus in GAC and this is working.
Steps:
1) [Download EEPlus(verstion 5.1.0)](https://nuget.info/packages/EPPlus/5.1.0) 
![image](https://user-images.githubusercontent.com/26743903/139245260-8509ec1c-b9e0-4299-b9aa-48066fea27c5.png)
Double click on EPPlus.dll
2) Run Developer Command Prompt as Admin. (You need visual studio for this)
3) Go to directory with library (for me `cd C:\Users\matematuk\Downloads`)
4) Run command `gacutil -i EPPlus.dll`
5) Restart entire XrmToolbox 

P.S. You can do this with regular Command Prompt as well but with few additional steps.

**Comment by rajyraman** [comment]
@MaTeMaTuK @ as080388 - This long standing issue is fixed in v2.8.3. Thank you to @BetimBeja for the help. Please update the plugin through XrmToolBox.
