### ISSUE TITLE
Export to excel dosen´t appear in Tool Library from XRMToolBox

### ISSUE THREAD

**Issue by voidMuyTofu** [rajyraman/mscrmexporttoexcel#23]
Hello I´m trying to download your extension to Xrmtoolbox but it isn´t appearing in the Xrmtoolbox store.

![image](https://user-images.githubusercontent.com/47901690/141129317-06ea115c-fdb6-4e55-91ab-ba32787f3794.png)

And i don´t have it downloaded as you can see here: 

![image](https://user-images.githubusercontent.com/47901690/141129484-b644ca9c-1442-4e0c-91d0-b181be9d2248.png)

**Comment by rajyraman** [comment]
I can see it under Data.
![image](https://user-images.githubusercontent.com/5035266/141212668-0b38c12c-216b-4849-bb37-9a7ace02d8e3.png)
