### ISSUE TITLE
Unable to properly connect to CRM2011 or export since last update

### ISSUE THREAD

**Issue by MEPVIC** [rajyraman/mscrmexporttoexcel#25]
Hello,
I've been using the tool for a while now to connect to CRM2011 onprem with no issues, but since the update last week an even after the latest releases I've been unable to use the tool. The most recent error on version 3.0.1 are
Upon opening the tool and connecting I get an unhandle exception.
![image](https://user-images.githubusercontent.com/94105631/141266843-921a11c2-e313-40a5-ac91-cab7e0ad6c2c.png)
If I attempt to export then I get a formatter error
![image](https://user-images.githubusercontent.com/94105631/141266967-ce1aae9a-06c6-4b8e-8c38-bdc76c0049ab.png)

Is there a way I can rollback to a previous working version of the tool.
Many thanks

**Comment by rajyraman** [comment]
@MEPVIC - I started using XrmToolBox controls (https://github.com/jamesnovak/xrmtb.XrmToolBox.Controls) to facilitate searching and paging in solutions. So, it might be a requirement/assumption by that library. I will see whether there is way to fix this locally.

**Comment by MEPVIC** [comment]
Hi Raj,
Thanks for the quick reply, I've got access to a D365 server as well and the first error only occurs when connecting to CRM2011, while the second happens in both.
Thanks

**Comment by rajyraman** [comment]
@MEPVIC - RetrieveTotalRecordCount is used for notifying the user of progress when the records are exported. It is applicable to only 9.1 onwards, so that is why it is erroring out on older versions.

**Comment by MEPVIC** [comment]
Hi Raj,
Apologies for the question as a feel I am not following your response.
Version 9.1 of which program?
I am running the latest version of XRMToolbox 1.2021.9.52, and the fault occurs on both 2011 and D365 versions, so what am I missing.
Is there any additional data / information that could assist you.
Thanks.
![image](https://user-images.githubusercontent.com/94105631/141698702-d7ed75b9-9882-4382-8770-139fdf5a4234.png)

**Comment by MEPVIC** [comment]
![image](https://user-images.githubusercontent.com/94105631/141698903-ebab140a-5e16-4a75-917c-a6dd298d3ade.png)

**Comment by rajyraman** [comment]
This should no longer be an issue with the latest version.

**Comment by MEPVIC** [comment]
Hi Raj,
Thank you very much for all the effort, I've finally gotten around to test the new version and unfortunately, I am still experiencing new problems the tool no longer loads any entities. I've tested a couple of other tools I use like the FetchXML, PowerQuery (M) Builder and  ReportSync and they all connect ok and display the entities as normal.
Please let me know if you require any further details from me.
Once again thank you for all your efforts

**Comment by rajyraman** [comment]
Are you using 3.0.3 https://www.nuget.org/packages/Ryr.XrmToolBox.ExportToExcel/?

Maybe delete the DLL from the Plugin folder and try installing again.

**Comment by MEPVIC** [comment]
Hi Raj,
I've uninstall XRMToolBox completely, downloaded the latest version again and started from scratch. Still the same.
I Can load entities in Chart Manager for example but not on the Export to Excel tool.
Not sure what to try next.

Is there a way I can rollback the tool to an earlier version when it used to work?

Thanks
