### ISSUE TITLE
XrmToolBox: Unable to connect to Export to Excel  since last update

### ISSUE THREAD

**Issue by afonsomcf** [rajyraman/mscrmexporttoexcel#26]
![error ](https://user-images.githubusercontent.com/94127906/141329455-6992b1b4-4562-4339-b81d-df09fe44d0dc.jpeg)

**Comment by rajyraman** [comment]
@afonsomcf - Can you expand the details and see what the error is? As soon as it connects the tool tries to get the list of solutions.

**Comment by andreasrgfischer** [comment]
I'm getting the same error on startup with following exception message:

System.InvalidOperationException: Die Sequenz enthält keine Elemente.
   bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   bei xrmtb.XrmToolBox.Controls.Utility.GetPropertyValue[T](Object data, PropertyInfo p, Int32 languageCode)
   bei xrmtb.XrmToolBox.Controls.FilteredListViewBaseControl.PopulateListView()
   bei xrmtb.XrmToolBox.Controls.EntitiesListControl.<LoadData>b__31_1(Object s, RunWorkerCompletedEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

The solutions are actually listed but the views aren't.

**Comment by afonsomcf** [comment]
@rajyraman

**Comment by rajyraman** [comment]
@afonsomcf - Please use the old version from NuGet for now. I might have to rollback the XrmToolBox component addition for solution grid and framework as well, as these seem to not work with older versions of CRM. I am unable to test these as I am working only with Online.

**Comment by MichelSteen** [comment]
> @afonsomcf - Please use the old version from NuGet for now. I might have to rollback the XrmToolBox component addition for solution grid and framework as well, as these seem to not work with older versions of CRM. I am unable to test these as I am working only with Online.

Having the same issue: With an online environment. Could you please elaborate how to use "the old version" ?

**Comment by rajyraman** [comment]
I pushed out a new version where I rolled back the grid control which doesn't seem to be working with older versions. I also added a check for record count API call which should fix this issue. Please update and check.

**Comment by afonsomcf** [comment]
@rajyraman works just fine! Thanks! ;) 
The only issue is that it takes more time to extract.

**Comment by rajyraman** [comment]
@afonsomcf - The new version which I pushed out today should fix the slowness too.

**Comment by afonsomcf** [comment]
@rajyraman  Thank You! It has an awesome performance now! 🚀 🚀
