### ISSUE TITLE
Getting an Error when trying to Export

### ISSUE THREAD

**Issue by MichaelRushton17** [rajyraman/mscrmexporttoexcel#28]
Getting this error when trying to export:

![image](https://user-images.githubusercontent.com/94860448/142907245-89180928-e427-49b6-9b7a-4c86b38ffe59.png)

**Comment by NT-Duong** [comment]
I have this same issue as well. I get a Microsoft .NET Framework exception error when loading the export to excel.
![image](https://user-images.githubusercontent.com/33711375/142930763-7969b5fd-b1a6-4f14-b292-7a27158b7972.png)

If hit continue and try to export anything I get the error message above.

**Comment by rajyraman** [comment]
@NT-Duong - This should no longer be an issue as I have already rolled back xtbgrid which needs recent version of Power Apps/Dynamics 365.
