### ISSUE TITLE
Can't export records with regardingobjectid in GUID

### ISSUE THREAD

**Issue by yotrainor** [rajyraman/mscrmexporttoexcel#3]
Hy, 

I have a question, I am using Export to excel plugin with fetchxmlbuilder. I want to export records in XLSX. It works well but I can't export the regardingobjectid in guid (export to excel convert the column with metadata in Excel...).

How can I do that ?

Thank you

**Comment by rajyraman** [comment]
This is by design, as this is also his OOB data export does it. If you want the ID you should use link entity that corresponds to the regardingobjectid and also retrieve its primary key.

**Comment by yotrainor** [comment]
Rah ok, I can't use link entity because I don't know if it is a Contact, Account, Lead ... I'm exporting PhoneCall & task records ...

So, I have to write so code to do the trick. 

Thank you raj
